export default {
    CENSUS_API_REQUEST: 'CENSUS_API_REQUEST',
    CENSUS_API_REQUEST_SUCCESS: 'CENSUS_API_REQUEST_SUCCESS',
    REQUEST_ERROR: 'REQUEST_ERROR',
    RESET_REQUEST_ERROR: 'RESET_REQUEST_ERROR'
}